### ISSUE TITLE
Variable "elementType" does not exist

### ISSUE THREAD

**Issue by dr-codswallop** [flipboxfactory/craft-element-lists#11]
Running Craft 3.5.2. Just installed plugin and can't edit entries in sections with this field any more. Returns with twig runtime error.

`Variable "elementType" does not exist.`
`in XXXXX/vendor/craftcms/cms/src/templates/_elements/sources.html at line 53`

` {{ sourceLink(key, source, not keyPrefix, elementType) }}`

Requirements say you support up to Craft 3.3.x. If incompatible with Craft 3.5.x any ideas on an update?

Craft 3.5.2
Elements List 3.1.0

**Comment by nateiler** [comment]
Look like the recent required changes here is causing this: https://github.com/craftcms/cms/commit/8678b515a539cef7d20e7464fdb0b62fe8179d52#diff-184ce609400df0ea3b938a89b899ba1dL4

I've updated the sub package which should resolve this issue.  Try running `composer update flipboxfactory/craft-elements-nested-index` which should bump to version 2.4.1

**Comment by dr-codswallop** [comment]
I'm afraid not @nateiler. I ran the composer update command but still receiving the same error

**Comment by nateiler** [comment]
Can you verify two dependency versions in your `composer.lock` file:

`flipboxfactory/craft-elements-nested-index` -> 2.4.1
`flipboxfactory/craft-element-lists` -> 3.1.0

If one of those is off, we'll try to get them updated

**Comment by dr-codswallop** [comment]
Here's the entries in my `composer.lock` file
```
"name": "flipboxfactory/craft-element-lists",
"version": "3.1.0",

"name": "flipboxfactory/craft-elements-nested-index",
"version": "2.4.1",
```
